<?php
/**
 * @file
 * usp_content_freshness_report.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function usp_content_freshness_report_field_default_fields() {
  $fields = array();

  // Exported field: 'node-article-field_content_review_due_date'.
  $fields['node-article-field_content_review_due_date'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_content_review_due_date',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'computed_field',
      'settings' => array(
        'code' => '$review_period = array_pop(array_pop(field_get_items($entity_type, $entity, \'field_content_review_period\')));

// date review is due is the current timestamp + the number of days in the review period multiplied by the number of seconds in a day
$entity_field[0][\'value\'] = $entity->changed + ($review_period * 86400);',
        'database' => array(
          'data_default' => '',
          'data_index' => 1,
          'data_length' => '32',
          'data_not_NULL' => 1,
          'data_precision' => '10',
          'data_scale' => '2',
          'data_size' => 'normal',
          'data_type' => 'int',
        ),
        'display_format' => '$display_output = date(\'m-d-Y\', $entity_field_item[\'value\']);',
        'store' => 1,
      ),
      'translatable' => '0',
      'type' => 'computed',
    ),
    'field_instance' => array(
      'bundle' => 'article',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'computed_field',
          'settings' => array(),
          'type' => 'computed_field_plain',
          'weight' => '13',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_content_review_due_date',
      'label' => 'Content Review Due Date',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'computed_field',
        'settings' => array(),
        'type' => 'computed',
        'weight' => '4',
      ),
    ),
  );

  // Exported field: 'node-article-field_content_review_period'.
  $fields['node-article-field_content_review_period'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_content_review_period',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          90 => 'Quarterly',
          180 => 'Biannually',
          365 => 'Annually',
        ),
        'allowed_values_function' => '',
      ),
      'translatable' => '0',
      'type' => 'list_integer',
    ),
    'field_instance' => array(
      'bundle' => 'article',
      'default_value' => array(
        0 => array(
          'value' => '90',
        ),
      ),
      'deleted' => '0',
      'description' => 'Select how often the content should be reviewed for accuracy and completeness.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => '12',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_content_review_period',
      'label' => 'Content Review Period',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '2',
      ),
    ),
  );

  // Exported field: 'node-department-field_content_review_due_date'.
  $fields['node-department-field_content_review_due_date'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_content_review_due_date',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'computed_field',
      'settings' => array(
        'code' => '$review_period = array_pop(array_pop(field_get_items($entity_type, $entity, \'field_content_review_period\')));

// date review is due is the current timestamp + the number of days in the review period multiplied by the number of seconds in a day
$entity_field[0][\'value\'] = $entity->changed + ($review_period * 86400);',
        'database' => array(
          'data_default' => '',
          'data_index' => 1,
          'data_length' => '32',
          'data_not_NULL' => 1,
          'data_precision' => '10',
          'data_scale' => '2',
          'data_size' => 'normal',
          'data_type' => 'int',
        ),
        'display_format' => '$display_output = date(\'m-d-Y\', $entity_field_item[\'value\']);',
        'store' => 1,
      ),
      'translatable' => '0',
      'type' => 'computed',
    ),
    'field_instance' => array(
      'bundle' => 'department',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'computed_field',
          'settings' => array(),
          'type' => 'computed_field_plain',
          'weight' => 4,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_content_review_due_date',
      'label' => 'Content Review Due Date',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'computed_field',
        'settings' => array(),
        'type' => 'computed',
        'weight' => '36',
      ),
    ),
  );

  // Exported field: 'node-department-field_content_review_period'.
  $fields['node-department-field_content_review_period'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_content_review_period',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          90 => 'Quarterly',
          180 => 'Biannually',
          365 => 'Annually',
        ),
        'allowed_values_function' => '',
      ),
      'translatable' => '0',
      'type' => 'list_integer',
    ),
    'field_instance' => array(
      'bundle' => 'department',
      'default_value' => array(
        0 => array(
          'value' => '365',
        ),
      ),
      'deleted' => '0',
      'description' => 'Select how often the content should be reviewed for accuracy and completeness.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 3,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_content_review_period',
      'label' => 'Content Review Period',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '34',
      ),
    ),
  );

  // Exported field: 'node-page-field_content_review_due_date'.
  $fields['node-page-field_content_review_due_date'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_content_review_due_date',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'computed_field',
      'settings' => array(
        'code' => '$review_period = array_pop(array_pop(field_get_items($entity_type, $entity, \'field_content_review_period\')));

// date review is due is the current timestamp + the number of days in the review period multiplied by the number of seconds in a day
$entity_field[0][\'value\'] = $entity->changed + ($review_period * 86400);',
        'database' => array(
          'data_default' => '',
          'data_index' => 1,
          'data_length' => '32',
          'data_not_NULL' => 1,
          'data_precision' => '10',
          'data_scale' => '2',
          'data_size' => 'normal',
          'data_type' => 'int',
        ),
        'display_format' => '$display_output = date(\'m-d-Y\', $entity_field_item[\'value\']);',
        'store' => 1,
      ),
      'translatable' => '0',
      'type' => 'computed',
    ),
    'field_instance' => array(
      'bundle' => 'page',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'computed_field',
          'settings' => array(),
          'type' => 'computed_field_plain',
          'weight' => 3,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_content_review_due_date',
      'label' => 'Content Review Due Date',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'computed_field',
        'settings' => array(),
        'type' => 'computed',
        'weight' => '1',
      ),
    ),
  );

  // Exported field: 'node-page-field_content_review_period'.
  $fields['node-page-field_content_review_period'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_content_review_period',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          90 => 'Quarterly',
          180 => 'Biannually',
          365 => 'Annually',
        ),
        'allowed_values_function' => '',
      ),
      'translatable' => '0',
      'type' => 'list_integer',
    ),
    'field_instance' => array(
      'bundle' => 'page',
      'default_value' => array(
        0 => array(
          'value' => '180',
        ),
      ),
      'deleted' => '0',
      'description' => 'Select how often the content should be reviewed for accuracy and completeness.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 2,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_content_review_period',
      'label' => 'Content Review Period',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '-1',
      ),
    ),
  );

  // Exported field: 'node-webform-field_content_review_due_date'.
  $fields['node-webform-field_content_review_due_date'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_content_review_due_date',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'computed_field',
      'settings' => array(
        'code' => '$review_period = array_pop(array_pop(field_get_items($entity_type, $entity, \'field_content_review_period\')));

// date review is due is the current timestamp + the number of days in the review period multiplied by the number of seconds in a day
$entity_field[0][\'value\'] = $entity->changed + ($review_period * 86400);',
        'database' => array(
          'data_default' => '',
          'data_index' => 1,
          'data_length' => '32',
          'data_not_NULL' => 1,
          'data_precision' => '10',
          'data_scale' => '2',
          'data_size' => 'normal',
          'data_type' => 'int',
        ),
        'display_format' => '$display_output = date(\'m-d-Y\', $entity_field_item[\'value\']);',
        'store' => 1,
      ),
      'translatable' => '0',
      'type' => 'computed',
    ),
    'field_instance' => array(
      'bundle' => 'webform',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'computed_field',
          'settings' => array(),
          'type' => 'computed_field_plain',
          'weight' => 4,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_content_review_due_date',
      'label' => 'Content Review Due Date',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 0,
        'module' => 'computed_field',
        'settings' => array(),
        'type' => 'computed',
        'weight' => '7',
      ),
    ),
  );

  // Exported field: 'node-webform-field_content_review_period'.
  $fields['node-webform-field_content_review_period'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_content_review_period',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => '0',
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          90 => 'Quarterly',
          180 => 'Biannually',
          365 => 'Annually',
        ),
        'allowed_values_function' => '',
      ),
      'translatable' => '0',
      'type' => 'list_integer',
    ),
    'field_instance' => array(
      'bundle' => 'webform',
      'default_value' => array(
        0 => array(
          'value' => '90',
        ),
      ),
      'deleted' => '0',
      'description' => 'Select how often the content should be reviewed for accuracy and completeness.',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 3,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_content_review_period',
      'label' => 'Content Review Period',
      'required' => 1,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '5',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Content Review Due Date');
  t('Content Review Period');
  t('Select how often the content should be reviewed for accuracy and completeness.');

  return $fields;
}
